version: '3.8'

services:
  app:
    build: .
    container_name: ostadbank_bot
    restart: always
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mariadb:10.11
    container_name: ostadbank_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: