# alembic/versions/a4_add_ratings.py
"""Adds rating columns to experiences table

Revision ID: a4
Revises: a3
Create Date: 2025-09-26 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4'
down_revision = 'a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiences', sa.Column('teaching_rating', sa.Enum('EXCELLENT', 'GOOD', 'AVERAGE', 'POOR', name='teachingrating'), nullable=True))
    op.add_column('experiences', sa.Column('exam_difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='examdifficulty'), nullable=True))
    op.add_column('experiences', sa.Column('overall_rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiences', 'overall_rating')
    op.drop_column('experiences', 'exam_difficulty')
    op.drop_column('experiences', 'teaching_rating')
    # ### end Alembic commands ###